import {useEffect,useRef,useState} from 'react';
import {ArrowLeft,ArrowRight,Images,Moon,Sun,X,Expand,View,BookOpen} from 'lucide-react';
import {useGarden} from '../state/store';
export interface Art {id:string;n:number;title:string;placeId:string|null;url:string;thumbnail:string;chapters:number[];width:number;height:number;sourceTitle:string;sourceUrl:string}
let catalogue:Promise<Art[]>|undefined;
function useArt(){const [images,setImages]=useState<Art[]>([]),[status,setStatus]=useState<'loading'|'ready'|'error'>('loading'),[attempt,setAttempt]=useState(0);useEffect(()=>{let live=true;setStatus('loading');catalogue??=fetch(import.meta.env.BASE_URL+'art/manifest.json').then(r=>{if(!r.ok)throw Error('图录载入失败');return r.json()});catalogue.then(items=>{if(live){setImages(items);setStatus('ready')}}).catch(()=>{catalogue=undefined;if(live)setStatus('error')});return()=>{live=false}},[attempt]);return {images,status,retry:()=>{catalogue=undefined;setAttempt(n=>n+1)}}}
const url=(path:string)=>import.meta.env.BASE_URL+path;
export function AtmosphereControl(){const time=useGarden(s=>s.timeOfDay);return <div className="atmosphere-control" aria-label="园林光照"><button aria-pressed={time==='day'} onClick={()=>useGarden.setState({timeOfDay:'day'})}><Sun size={15}/>晨光</button><button aria-pressed={time==='night'} onClick={()=>useGarden.setState({timeOfDay:'night'})}><Moon size={15}/>月夜</button></div>}
export function GalleryButton(){return <button className="gallery-open" onClick={()=>useGarden.setState({galleryOpen:true,activeImageId:null})}><Images size={17}/>园景图录</button>}
export function PlaceReference({placeId}:{placeId:string}){const {images:all}=useArt(),s=useGarden();const pics=all.filter(a=>a.placeId===placeId&&(s.spoilerLimit===null||Math.min(...a.chapters)<=s.spoilerLimit));const selected=pics[0];if(!selected)return null;return <figure className="place-reference"><button onClick={()=>useGarden.setState({galleryOpen:true,activeImageId:selected.id})} aria-label={'放大'+selected.title}><img src={url(selected.url)} alt={selected.title+'，孙温绘本原图'} loading="lazy" width={selected.width} height={selected.height}/><span><Expand size={15}/>孙温绘本</span></button><figcaption>清代绘本原图 · 点击对照建筑与色彩</figcaption></figure>}
export function ViewControls(){
 const s=useGarden(),p=s.data?.manifest.places.find(p=>p.id===s.selectedPlaceId);
 if(!p)return null;
 const inside=s.hotspotId===p.id+'-study';
 return <>
  <div className="view-controls"><button aria-pressed={!s.hotspotId} onClick={()=>useGarden.setState({hotspotId:null,cutaway:false,closeView:false})}><View size={14}/>院落全貌</button>{p.interiorCamera&&<button aria-pressed={inside&&!s.cutaway} onClick={()=>useGarden.setState({hotspotId:p.id+'-study',cutaway:false})}><BookOpen size={14}/>{p.id==='daguanlou'?'层楼细看':'屋内陈设'}</button>}<button aria-pressed={inside&&s.cutaway} onClick={()=>useGarden.setState({hotspotId:p.id+'-study',cutaway:true})}><Expand size={14}/>剖视结构</button></div>
  <label className="detail-point-picker"><span>院内细节</span><select value={s.hotspotId??''} onChange={event=>useGarden.setState({hotspotId:event.target.value||null,cutaway:false})}><option value="">选择一处细看</option>{p.hotspots.map((point,index)=><option key={point.id} value={point.id}>{index+1} · {point.name}</option>)}</select></label>
 </>;
}
function ReferenceImage({art}:{art:Art}){
 const [status,setStatus]=useState<'loading'|'ready'|'error'>('loading'),[attempt,setAttempt]=useState(0);
 return <div className="gallery-image" aria-busy={status==='loading'}>
  <img key={attempt} src={url(art.url)+(attempt?'?retry='+attempt:'')} alt={art.title} width={art.width} height={art.height} onLoad={()=>setStatus('ready')} onError={()=>setStatus('error')} hidden={status==='error'}/>
  {status!=='ready'&&<div className="image-status" role="status">{status==='error'?<><p>这幅园景暂时未能载入。</p><button onClick={()=>{setStatus('loading');setAttempt(n=>n+1)}}>重新载入这幅图片</button></>:<p>正在展开园景图片…</p>}</div>}
 </div>
}
export function ReferenceGallery(){const s=useGarden(),{images:all,status,retry}=useArt(),dialog=useRef<HTMLDialogElement>(null);const images=all.filter(a=>s.spoilerLimit===null||Math.min(...a.chapters)<=s.spoilerLimit);const active=images.find(a=>a.id===s.activeImageId);const at=active?images.indexOf(active):-1;const close=()=>useGarden.setState({galleryOpen:false});useEffect(()=>{if(s.galleryOpen&&!dialog.current?.open)dialog.current?.showModal();if(!s.galleryOpen&&dialog.current?.open)dialog.current?.close()},[s.galleryOpen]);useEffect(()=>{const key=(e:KeyboardEvent)=>{if(!s.galleryOpen||at<0)return;if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();useGarden.setState({activeImageId:images[(at+(e.key==='ArrowRight'?1:images.length-1))%images.length].id})}};document.addEventListener('keydown',key);return()=>document.removeEventListener('keydown',key)},[s.galleryOpen,at,images]);return <dialog className="reference-gallery" ref={dialog} onCancel={close} aria-label="大观园参考图录"><header><div><h2>{active?.title??'孙温笔下的大观园'}</h2><p>清代孙温《红楼梦》绘本原图 · 本园建筑配色与花木疏密的美术依据。</p>{active&&<a href={active.sourceUrl} target="_blank" rel="noreferrer">原图出处 · {active.sourceTitle}</a>}</div><button className="icon-button" onClick={close} aria-label="关闭图录"><X size={23}/></button></header>{active?<><div className="gallery-large"><ReferenceImage key={active.id} art={active}/></div><footer><button onClick={()=>useGarden.setState({activeImageId:null})}><Images size={16}/>全部园景</button><div><button aria-label="上一幅参考图" onClick={()=>useGarden.setState({activeImageId:images[(at+images.length-1)%images.length].id})}><ArrowLeft size={18}/></button><span>{at+1} / {images.length}</span><button aria-label="下一幅参考图" onClick={()=>useGarden.setState({activeImageId:images[(at+1)%images.length].id})}><ArrowRight size={18}/></button></div>{active.placeId&&<button className="enter-reference" onClick={()=>{s.choosePlace(active.placeId);close()}}>进入此处三维园景 <ArrowRight size={16}/></button>}</footer></>:<div className="reference-grid">{images.map(a=><button key={a.id} onClick={()=>useGarden.setState({activeImageId:a.id})}><img src={url(a.thumbnail)} alt={a.title} loading="lazy" width="480" height="320"/><span>{a.title}</span><small>原著第 {a.chapters.join('、')} 回</small></button>)}{!images.length&&<div className="gallery-status" role="status">{status==='loading'?<p>图录正在展开，请稍候。</p>:status==='error'?<><p>图录暂时未能载入。</p><button onClick={retry}>重新载入图录</button></>:<p>当前阅读进度内暂无园景图片。可在游园设置中调整阅读进度。</p>}</div>}</div>}</dialog>}
