import {Download, RotateCcw, Trash2} from 'lucide-react';
import type {CanonData} from '../data/types';
import {useSimulation, exportEvidenceReport, exportJournal} from '../simulation/store';
import {agentIds} from '../simulation/types';
import {agentColors, currentWorld} from '../simulation/world';
import {compareBranches, knowledgeTrail} from '../simulation/insights';
import {spotName} from '../simulation/space';

export function SimulationFlow() {
  const s = useSimulation(), world = currentWorld(s.journal!), trail = knowledgeTrail(s.journal!);
  const points = {baoyu: [76, 42], daiyu: [244, 42], baochai: [76, 152], wangxifeng: [244, 152]};
  const edges = [...new Set(trail.map(e => `${e.agent}:${e.target}`))].map(key => { const event = trail.find(e => `${e.agent}:${e.target}` === key)!; return {key, from: event.agent!, to: event.target!, count: trail.filter(e => `${e.agent}:${e.target}` === key).length}; });
  return <section className="sim-flow"><h3>一句话，如何传遍园中</h3><p className="sim-note">连线只记录已完成的消息转述。点选人物可查看其所知；未传达的消息不会出现连线。</p><svg viewBox="0 0 320 194" role="img" aria-label={`消息传播图，已发生 ${trail.length} 次转述`}><defs><marker id="sim-arrow" markerWidth="7" markerHeight="7" refX="6" refY="3.5" orient="auto"><path d="M0 0L7 3.5L0 7" fill="var(--jade)"/></marker></defs>{edges.map(edge => { const [x1, y1] = points[edge.from], [x2, y2] = points[edge.to], angle = Math.atan2(y2 - y1, x2 - x1); return <g key={edge.key}><path d={`M${x1 + Math.cos(angle) * 31} ${y1 + Math.sin(angle) * 23} Q${(x1 + x2) / 2 + Math.sin(angle) * 14} ${(y1 + y2) / 2 - Math.cos(angle) * 14} ${x2 - Math.cos(angle) * 34} ${y2 - Math.sin(angle) * 24}`} fill="none" stroke="var(--jade)" strokeWidth="1.4" markerEnd="url(#sim-arrow)"/><title>{world.agents[edge.from].name}告知{world.agents[edge.to].name}，{edge.count}次</title></g>; })}{agentIds.map(id => <g key={id} transform={`translate(${points[id].join(' ')})`}><rect x="-33" y="-19" width="66" height="38" rx="2" fill="var(--paper-light)" stroke={agentColors[id]}/><text textAnchor="middle" dy="5" fill="var(--ink)">{world.agents[id].name}</text></g>)}</svg><div className="sim-flow-people">{agentIds.map(id => <button key={id} onClick={() => s.inspect(id)}>{world.agents[id].name}<span>{world.agents[id].memories.filter(m => m.type === 'knowledge').length} 条知情</span></button>)}</div>{trail.length ? <ol className="sim-flow-events">{trail.slice(-12).reverse().map(e => <li key={e.id}><span>Tick {e.tick} · {world.agents[e.agent!].name} → {world.agents[e.target!].name}</span><p>{e.text}</p><details><summary>核对事件</summary><p>{e.id}</p><p>{e.reason}</p></details></li>)}</ol> : <div className="sim-empty"><p>此刻，消息仍藏在个人心里。</p><span>创建“提前知情”条件并运行，观察人物何时选择开口。</span></div>}<button className="sim-export" onClick={exportEvidenceReport}><Download size={15}/>导出有事件依据的推演纪要</button></section>;
}
export function SimulationWorldlines({data}: {data: CanonData}) {
  const s = useSimulation(), journal = s.journal!, busy = s.phase !== 'ready', comparison = compareBranches(journal);
  return <section className="sim-worldlines"><h3>同一时刻，不同选择</h3><p className="sim-note">只比较同一文学起点、同 Tick 的完整快照。差异是这次演算的观察，不能直接等同于唯一因果。</p>{comparison?.main ? <><p className="sim-comparison-time">Tick {comparison.alternate.tick} · 主世界 / IF 世界</p><div className="sim-comparison">{comparison.changes.map(change => <div key={change.id}><h4>{change.after.name}</h4><p><span>主</span>{spotName(data, change.before.location, change.before.spot)}<br/><span>IF</span>{spotName(data, change.after.location, change.after.spot)}</p><small>平静差值 {change.calmDelta > 0 ? '+' : ''}{change.calmDelta} · IF 额外知情 {change.learned.length} 条</small></div>)}</div></> : <div className="sim-empty"><p>{journal.if ? `主世界尚无同一起点、Tick ${comparison?.alternate.tick} 的可用记录。` : '还没有第二种可能。'}</p><span>{journal.if ? '不同回目的剧情起点不直接比较。相同起点可在运行到同 Tick 后对照。' : '在园中纪事里创建一个 IF 条件。'}</span></div>}
    <h3>保留的世界线 <span>{journal.archives.length}/3</span></h3><p className="sim-note">创建新 IF 时，当前 IF 会移入这里。恢复时两条线交换，进度均保留。删除历史线前可先导出全部存档。</p>{journal.archives.length ? <ol className="sim-archives">{journal.archives.map(archive => <li key={archive.id}><strong>{archive.name}</strong><p>从 Tick {archive.branch.forkTick} 分岔 · 已至 Tick {archive.branch.snapshots[archive.branch.cursor].worldState.tick}</p><div><button disabled={busy} onClick={() => s.resumeBranch(archive.id)}><RotateCcw size={14}/>恢复这条世界线</button><button disabled={busy} aria-label={`删除历史线：${archive.name}`} onClick={() => s.deleteArchive(archive.id)}><Trash2 size={14}/>删除</button></div></li>)}</ol> : <p className="sim-note">尚无历史线。现有 IF 会在下次创建分支时自动保留。</p>}<button className="sim-export" onClick={exportJournal}><Download size={15}/>导出所有世界与快照</button><button className="sim-export" onClick={exportEvidenceReport}><Download size={15}/>导出推演纪要</button>
  </section>;
}
