"""Deterministic botanical material swatches, not rendered garden imagery."""
from pathlib import Path
import json,hashlib
import numpy as np
from PIL import Image,PngImagePlugin
R=Path(__file__).resolve().parents[1]
out=R/'assets/processed/focal-r12-fix2';out.mkdir(parents=True,exist_ok=True)
records=[]
for name,w,h,base in [('banana',256,512,(101,122,61)),('bamboo',128,256,(96,119,62)),('stem',128,256,(109,123,66)),('petal',128,128,(202,155,148)),('litter',128,128,(87,71,43))]:
 y,x=np.mgrid[0:h,0:w];u=x/(w-1);v=y/(h-1);rng=np.random.default_rng(12911+len(name))
 broad=np.sin(v*17+u*5)*.5+np.sin(v*43-u*13)*.24+rng.normal(0,.09,(h,w))
 mid=np.exp(-((u-.5)/(.016 if name=='banana' else .035))**2)
 vein=np.maximum(0,np.cos((v-abs(u-.5)*(.22 if name=='banana' else .36))*np.pi*(74 if name=='banana' else 28)))**12
 edge=np.clip((abs(u-.5)-.39)*9,0,1)*(1+.2*np.sin(v*75))
 age=np.clip((v-.83)*7,0,1)*(1+.15*np.sin(u*33))
 col=np.empty((h,w,3),dtype=float)
 for c,value in enumerate(base):col[:,:,c]=value+broad*(13 if name=='banana' else 8)
 if name in ['banana','bamboo']:
  col+=mid[:,:,None]*np.array([25,27,11])+vein[:,:,None]*np.array([8,10,3])
  col+=edge[:,:,None]*np.array([11,-2,4])+age[:,:,None]*np.array([13,4,3])
 elif name=='stem':col+=(np.sin(u*57)+.35*np.sin(u*123))[:,:,None]*np.array([7,8,3])
 else:col+=np.exp(-((u-.5)**2+(v-.5)**2)*7)[:,:,None]*np.array([26,26,22])
 path=out/f'{name}.png';meta=PngImagePlugin.PngInfo();origin='Locally authored deterministic botanical swatch, generated by scripts/bake_focal_foliage.py; veins, midrib and age variation are artistic interpretation, not a photographed or AI-generated garden.';meta.add_text('Origin',origin)
 Image.fromarray(np.clip(col,0,255).astype('uint8')).save(path,pnginfo=meta,optimize=True)
 record={'file':path.relative_to(R).as_posix(),'sha256':hashlib.sha256(path.read_bytes()).hexdigest(),'origin':origin,'prompt':origin+' The provenance field records the authored material intent; no image-generation model was used.','generatorSha256':hashlib.sha256(Path(__file__).read_bytes()).hexdigest(),'size':[w,h]}
 path.with_suffix('.png.json').write_text(json.dumps(record,indent=2),encoding='utf8');records.append(record)
(out/'manifest.json').write_text(json.dumps({'revision':'r12-fix2','files':records},indent=2),encoding='utf8')
print('Authored focal foliage swatches',len(records))
