"""Record the actual reference-world release without retaining old benchmark claims."""
from pathlib import Path
import json
R=Path(__file__).resolve().parents[1]
def write(path,text):
 p=R/path;t=p.with_name(p.name+'.next');t.write_text(text.strip()+'\n',encoding='utf8');t.replace(p)
write('README.md','''# 大观园 · 入梦

以《红楼梦》原文和十五幅园景参考图为依据的可交互三维园林。点击景点，旋转近看院落、进入屋内、查看结构剖视，并展开原文出处与参考图。

[在线游园](https://daguanyuan-rumeng.zeabur.app/) · 用户既有 Zeabur 加利福尼亚服务。最新部署是否验证通过，以 `reports/acceptance/zeabur-deployment.json` 的时间及 `health.assetRevision` 为准。

![实际浏览器全园截图](.impeccable/review/desktop.png)

## 本轮重建

15 处景点使用一份连续的地形、水岸、道路和位置配置。新增大观楼、栊翠庵、暖香坞；重新制作屋顶瓦垄、木构、花格、山石与室内陈设，增加实例化树木和日夜光照。图录保留全部 15 幅美术参考，可直接跳转到对应三维景点。

实时模型尚未达到参考图的照片级效果。布局、背面结构、尺度及色彩是美术解释；书中明确的景物与陈设另列原文证据。当前不是参考图逐像素复刻，也不是历史建筑测绘复原。

## 启动与构建

```powershell
npm ci
npm run dev
```

浏览器打开终端地址。已附带模型，普通启动无需 Blender。正式构建使用 `npm run build`，`npm start` 从 `dist/` 提供 HTTP 服务；不能用 file 协议双击 HTML。

```powershell
npm run assets:fetch
npm run content:prepare
npm run models:build
npm run models:optimize
npm run build
```

完整资产重建需要 Node、Python（requests、beautifulsoup4、Pillow、numpy）与 Blender。Windows 已验证 Blender 4.5.9 LTS；可用 `BLENDER_BIN` 指定另一安装路径。模型优化通过独立进程完成解码和验证，再原子替换，避免 Windows 映射文件锁。

## 游园操作

- 拖动旋转，滚轮缩放，右键平移；手机支持触摸旋转及双指操作。
- 点击画布名签、索引或小地图进入景点；“院落全貌”“屋内陈设”“剖视结构”分别控制对应视角。露天景点不显示不存在的屋内视角。
- 晨光／月夜切换照明；园景图录支持放大、左右切换和进入三维景点，载入失败可重试。
- 人物、回目及事件联动原文来源；设置中提供防剧透与阅读进度。
- 三条导览沿道路图行进，每站停留约 5 秒；可暂停、继续、前后站或退出。它们是策划路线，并非原著完整人物行迹。
- 手机默认轻量模型、DPR 1、低分辨率反射及按需渲染；选择地点后加载独立手机分区。

## 交付文件

| 路径 | 内容 |
|---|---|
| `blender/daguanyuan_master.blend` | 15 景点可编辑母场景，保留 Manual_Adjustments |
| `config/garden.layout.json` | 统一位置、道路、湖岸与镜头配置 |
| `blender/reference_scene.py` | 母场景生成入口 |
| `blender/reference_world.py` / `reference_craft.py` | 地形、园林、屋面和陈设构件 |
| `public/models/` | 2 总览、30 地点分区、2 植被原型，共 34 个压缩 GLB |
| `public/textures/shared/` | 按内容哈希共享的本地材质贴图 |
| `public/art/` | 15 幅大图与 15 幅缩略图，WebP 及生成提示词记录 |
| `output/imagegen/daguanyuan-reference-20260910/` | 原始 PNG、图录、提示词和来源说明 |
| `data/canon/` | 15 地点、13 人物、22 事件、46 来源、3 导览 |
| `assets/manifest.json` | 外部资源许可、来源、原文件和衍生哈希 |
| `reports/acceptance/` | 数据、模型、浏览器、性能及部署检查记录 |

重建仅替换生成集合，手动改动应保存在 `Manual_Adjustments`。本轮开始前的母场景与布局保存在 `.checkpoints/before-reference-world-20260910/`。历史潇湘馆样板保留，非当前全园入口。

运行 `npm run typecheck`、`npm run lint`、`npm test`、`npm run verify`、`npm run test:e2e` 检查代码与交互。性能方法和局限见 [PERFORMANCE](docs/PERFORMANCE.md)，部署见 [DEPLOYMENT](docs/DEPLOYMENT.md)，视觉边界见 [KNOWN_ISSUES](docs/KNOWN_ISSUES.md)。
''')
write('docs/KNOWN_ISSUES.md','''# 当前边界 · 参考图重建版

- 实时模型仍未达到参考图的照片级材质、植被形态与空间层次。独立视觉复核的最后完整结论是 REBUILD；之后修正了室内视角、花叶形状、背景树根、水岸连接和触摸尺寸，但不能把这些修正宣布为整体验收通过。
- 园区方位、比例、背面结构是美术解释。十五张单视角参考图不足以唯一确定完整三维几何；书中景物和陈设证据在界面单独列出。
- 精细模式保留更多瓦片、植物与纹理；手机采用简化分区与顶点色材质，近景细节会减少。性能数据以本轮 reports/acceptance/performance.json 和 mobile-4g.json 为准，旧版数值不适用。
- 尚未执行真实 iOS/Android 手机 GPU、Safari、长时间发热或内存压力测试。触摸和限速模拟不能保证所有手机稳定流畅。
- 三维交互是轨道观察、屋内预设镜头、结构剖视和道路图导览；未提供任意第一人称碰撞行走。室内可继续拖动观察，但未做墙体碰撞限制。
- 22 个事件是精选阅读内容，并非全书索引。数字文本来自维基文库，保留章节、版本和哈希，尚未经人类红学专家审定。
- 不使用未获得许可的完整古建模型；建筑由本项目构件生成，山石、树木来源与八项 CC0 资源记录在 assets/manifest.json。参考图是生成美术资产，不能作为原著考据证据。
- 未启用环境音乐、实时人物在场、OpenStory 或 AI 人物服务。
- 线上服务在用户既有加利福尼亚服务器；跨地域网络速度取决于访问网络。本机此前出现代理 DNS / HTTP3 连接问题，最新验证记录说明是否使用仅限测试浏览器的解析覆盖；不修改操作系统网络设置。
''')
p=R/'THIRD_PARTY_NOTICES.md';s=p.read_text(encoding='utf8').replace('- Forest Grove: environment lighting for Blender reference renders.', '- Forest Grove: local HDR environment lighting for the live scene and Blender.\n- Island Tree 01: source branch and leaf geometry; decimated trunk and sampled instanced foliage.\n- Leafy Grass: ground texture.\n- Mossy Cobblestone: paving and stone detail texture.\n- Worn Mossy Plasterwall: wall texture; tinted in the runtime shader.\n\nExact source identifiers and author attribution take precedence in assets/manifest.json. Shared JPEG material maps are encoded locally at quality 83; geometry and image derivatives have recorded SHA-256 hashes. The compound-leaf alpha mask is generated by project code. Fifteen generated visual references retain their original prompts and generation records.').replace('and vegetation modules were authored procedurally for this project.', 'and supplementary vegetation modules were authored procedurally for this project; the broadleaf tree prototype is derived from the licensed source above.')
write('THIRD_PARTY_NOTICES.md',s)
p=R/'docs/PROGRESS.md';s=p.read_text(encoding='utf8');s=s.replace('# ', '# Historical record — ',1) if not s.startswith('# Historical') else s
write('docs/PROGRESS.md',s+'\n\n## 2026-09-10 — 参考图整体重建（当前）\n\n旧版 G0—G5 数值仅为历史记录。当前为 15 地点、34 个 GLB，新增统一水岸、植被实例、分区室内镜头、图录与日夜交互。母场景重开检查为 1325 个网格、18 张打包图片，无缺失图片，保留 Manual_Adjustments。1,296 项完整性检查通过，六项单元测试通过；最新浏览器和部署状态以同目录 acceptance 报告时间为准。视觉复核尚未达到参考图写实要求，具体边界列于 KNOWN_ISSUES.md。\n')
