import {chromium} from 'playwright';
import {writeFileSync,readFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
const browser=await chromium.launch({channel:'msedge',headless:true});const page=await browser.newPage({viewport:{width:1440,height:900}});
await page.goto('http://127.0.0.1:4175/');await page.waitForFunction(()=>window.__gardenTest?.state().loaded);await page.waitForTimeout(6000);
async function capture(mode){return page.evaluate(mode=>{
 const c=document.querySelector('canvas'),gl=c.getContext('webgl2'),ext=gl.getExtension('WEBGL_debug_renderer_info');
 const geometries=new Set(),textures=new Set();let geometryBytes=0,textureBytes=0;
 window.__gardenTest.scene.traverse(o=>{if(o.geometry&&!geometries.has(o.geometry)){geometries.add(o.geometry);for(const a of Object.values(o.geometry.attributes))geometryBytes+=a.array.byteLength;if(o.geometry.index)geometryBytes+=o.geometry.index.array.byteLength}for(const m of Array.isArray(o.material)?o.material:o.material?[o.material]:[])for(const v of Object.values(m)){if(v?.isTexture&&!textures.has(v)){textures.add(v);const im=v.image;if(im?.width&&im?.height)textureBytes+=im.width*im.height*4*4/3}}});
 const metrics=window.__gardenMetrics,frames=metrics.frames.filter(x=>x>0&&x<250).slice(-300),sorted=[...frames].sort((a,b)=>a-b);return {mode,timestamp:new Date().toISOString(),userAgent:navigator.userAgent,viewport:[innerWidth,innerHeight],dpr:metrics.dpr,renderer:ext?gl.getParameter(ext.UNMASKED_RENDERER_WEBGL):gl.getParameter(gl.RENDERER),vendor:ext?gl.getParameter(ext.UNMASKED_VENDOR_WEBGL):gl.getParameter(gl.VENDOR),sampleCount:frames.length,meanFrameMs:frames.reduce((a,b)=>a+b,0)/frames.length,p95FrameMs:sorted[Math.floor(sorted.length*.95)],drawCalls:metrics.drawCalls,triangles:metrics.triangles,estimatedGeometryBytes:geometryBytes,estimatedTextureBytesWithMipmaps:textureBytes,textureCount:textures.size,geometryCount:geometries.size,resources:performance.getEntriesByType('resource').map(r=>({name:r.name,transferSize:r.transferSize,decodedBodySize:r.decodedBodySize})),method:mode==='high'?'6-second settled static overview with water animation; last up to 300 frames; no network throttling':'Orbit interaction on low quality; demand rendering; idle frame rate is not a meaningful measure'};
 },mode)}
const high=await capture('high');await page.getByRole('button',{name:'游园设置',exact:true}).click();await page.getByRole('combobox',{name:'画面精度'}).selectOption('low');await page.getByRole('button',{name:'关闭设置',exact:true}).click();await page.waitForTimeout(2000);
await page.evaluate(()=>{window.__gardenMetrics.frames.length=0});const box=await page.locator('canvas').boundingBox();await page.mouse.move(box.x+box.width*.5,box.y+box.height*.45);await page.mouse.down();for(let i=0;i<150;i++){await page.mouse.move(box.x+box.width*.5+Math.sin(i/25)*140,box.y+box.height*.45+Math.cos(i/25)*25);await page.waitForTimeout(16)}await page.mouse.up();await page.waitForTimeout(600);const low=await capture('low');
writeFileSync('reports/acceptance/performance.json',JSON.stringify({conditions:{os:'Windows 11',headless:true,actualMobileHardware:false,network:'local HTTP; no throttling',overviewSha256:createHash('sha256').update(readFileSync('public/models/overview.glb')).digest('hex'),metricLimit:'GPU allocations are estimates from scene resources; excludes driver overhead/framebuffers and cached hidden assets. These are not total VRAM readings.'},high,low},null,2));console.log({high:{meanMs:high.meanFrameMs,p95Ms:high.p95FrameMs,drawCalls:high.drawCalls,triangles:high.triangles,renderer:high.renderer},low:{meanMs:low.meanFrameMs,p95Ms:low.p95FrameMs,drawCalls:low.drawCalls,triangles:low.triangles}});await browser.close();
