import {chromium} from 'playwright';
import {writeFileSync,readFileSync} from 'node:fs';
import {replaceFile} from './atomic_replace.mjs';
const save=(path,data)=>{writeFileSync(path+'.next',data);replaceFile(path+'.next',path)};
const url=process.env.APP_URL||'http://127.0.0.1:4273/';
const reportPath=process.env.GARDEN_SMOKE_REPORT||'reports/acceptance/production-smoke.json';
const shotPrefix=process.env.GARDEN_SMOKE_SCREEN_PREFIX;
// Optional per-browser DNS override for a newly provisioned domain behind local
// proxy DNS caches. TLS verification stays enabled and OS settings stay intact.
const resolveIp=process.env.APP_RESOLVE_IP;
const loadTimeout=Number(process.env.GARDEN_LOAD_TIMEOUT_MS||90000);
if(!Number.isFinite(loadTimeout)||loadTimeout<1||loadTimeout>600000)throw Error('Invalid observation timeout');
const browser=await chromium.launch({channel:'msedge',headless:true,args:resolveIp?[`--host-resolver-rules=MAP ${new URL(url).hostname} ${resolveIp}`,'--disable-quic']:[]});
const page=await browser.newPage({viewport:{width:1440,height:900}}),errors=[],failed=[];
page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.status()>=400)failed.push(r.url())});
page.on('console',m=>{if(m.type()==='error'&&/THREE.WebGLProgram|shader error|GL_INVALID/.test(m.text()))errors.push(m.text())});
const desktopStarted=Date.now();
await page.goto(url);await page.getByRole('button',{name:'定位潇湘馆',exact:true}).waitFor({timeout:loadTimeout});
await page.locator('.canvas-wrap[data-scene-ready="true"]').waitFor({timeout:loadTimeout});
const desktopReadyMs=Date.now()-desktopStarted;
const hooksAbsent=await page.evaluate(()=>!window.__gardenTest&&!window.__gardenMetrics&&!window.__simulationTest);
const health=await page.evaluate(()=>fetch('/healthz').then(r=>r.json()));
const expectedRevision=JSON.parse(readFileSync('public/scene-manifest.json','utf8')).assetRevision;
if(health.status!=='ok'||health.revision!==expectedRevision)throw Error('Production is serving a different scene revision');
await page.getByRole('button',{name:'俯瞰全园布局',exact:true}).focus();await page.keyboard.press('Enter');
if(await page.getByRole('button',{name:'俯瞰全园布局',exact:true}).getAttribute('aria-pressed')!=='true')throw Error('Plan view control did not activate');
await page.getByRole('button',{name:'回到全园',exact:true}).click();
await page.getByRole('button',{name:'展开索引',exact:true}).click();
await page.getByRole('textbox',{name:'搜索园中内容'}).focus();
const focus=await page.getByRole('textbox',{name:'搜索园中内容'}).evaluate(e=>({width:getComputedStyle(e).outlineWidth,style:getComputedStyle(e).outlineStyle}));
await page.locator('.place-row').filter({hasText:'潇湘馆'}).click();await page.locator('.detail-scroll h2').filter({hasText:'潇湘馆'}).waitFor();
await page.reload();await page.getByRole('button',{name:'定位潇湘馆',exact:true}).waitFor({timeout:loadTimeout});
await page.locator('.canvas-wrap[data-scene-ready="true"]').waitFor({timeout:loadTimeout});await page.waitForLoadState('networkidle');await page.waitForTimeout(1200);
const build=JSON.parse(readFileSync('dist/.vite/manifest.json','utf8'));
const sourceHooksAbsent=Object.values(build).filter(entry=>entry.file.endsWith('.js')).every(entry=>!/__gardenTest|__gardenMetrics|__simulationTest/.test(readFileSync('dist/'+entry.file,'utf8')));
save(shotPrefix?shotPrefix+'-desktop.png':'reports/browser/13-production-desktop.png',await page.screenshot());
const desktopResult={at:new Date().toISOString(),url:page.url(),revision:health.revision,planView:true,dnsOverride:resolveIp??null,quicDisabled:!!resolveIp,tlsVerification:new URL(url).protocol==='https:'?true:null,observationTimeoutMs:loadTimeout,desktopReadyMs,hooksAbsent,sourceHooksAbsent,focus,sceneVisible:true,refresh:true,selection:true,errors,failed};
await page.close(); // Each device sample has one active WebGL page.
const mobile=await browser.newPage({viewport:{width:390,height:844},deviceScaleFactor:3,isMobile:true,hasTouch:true});
const mobileModels=[];mobile.on('response',r=>{if(r.url().endsWith('.glb'))mobileModels.push(new URL(r.url()).pathname)});
mobile.on('pageerror',e=>errors.push(e.message));mobile.on('response',r=>{if(r.status()>=400)failed.push(r.url())});
mobile.on('console',m=>{if(m.type()==='error'&&/THREE.WebGLProgram|shader error|GL_INVALID/.test(m.text()))errors.push(m.text())});
const mobileStarted=Date.now();
await mobile.goto(url);await mobile.locator('canvas').waitFor();
await mobile.locator('.canvas-wrap[data-scene-ready="true"]').waitFor({timeout:loadTimeout});
const mobileReadyMs=Date.now()-mobileStarted;
const mobilePartition=mobile.waitForResponse(r=>r.url().includes('/models/places-low/xiaoxiangguan.glb')&&r.ok());
await mobile.getByRole('button',{name:'展开索引',exact:true}).click();await mobile.locator('.place-row').filter({hasText:'潇湘馆'}).click();await mobile.locator('.detail-scroll h2').filter({hasText:'潇湘馆'}).waitFor();
const partition=await mobilePartition;await partition.finished();await mobile.waitForLoadState('networkidle');
await mobile.locator('[data-detail-ready="xiaoxiangguan"]').waitFor({timeout:loadTimeout});
await mobile.getByRole('button',{name:'看全院',exact:true}).tap();
await mobile.getByRole('button',{name:'拉近院景',exact:true}).tap();
await mobile.waitForTimeout(2500);
await mobile.getByRole('button',{name:'曲廊与竹径',exact:true}).tap();
await mobile.locator('.hotspot-note strong').filter({hasText:'曲廊与竹径'}).waitFor();
await mobile.getByRole('combobox',{name:'院内细节',exact:true}).selectOption('xiaoxiangguan-garden');
await mobile.locator('.hotspot-note strong').filter({hasText:'竹下泉渠'}).waitFor();
await mobile.getByRole('button',{name:'院落全貌',exact:true}).tap();await mobile.waitForTimeout(1800);
await mobile.getByRole('button',{name:'拉近院景',exact:true}).tap();await mobile.waitForTimeout(1800);
save(shotPrefix?shotPrefix+'-mobile.png':'reports/browser/14-production-mobile.png',await mobile.screenshot());
const result={...desktopResult,mobile:{viewport:[390,844],touchEmulation:true,networkThrottle:false,concurrentDesktopPage:false,readyMs:mobileReadyMs,models:mobileModels,selection:true,hotspotTap:true,equivalentDetailPicker:true,closeAndFullCourtyard:true}};
save(reportPath,JSON.stringify(result,null,2));await browser.close();
if(!hooksAbsent||!sourceHooksAbsent||focus.width!=='2px'||focus.style!=='solid'||errors.length||failed.length||!mobileModels.includes('/models/overview-low.glb')||mobileModels.includes('/models/overview.glb'))throw Error(JSON.stringify(result));
console.log('Production smoke passed: load, selection, refresh, keyboard focus, no debug hooks, no errors.');
