// GLB may reference local external images. Share identical embedded maps across
// independently loaded LODs instead of downloading the same maps per place.
import {readFileSync,writeFileSync,mkdirSync,existsSync,readdirSync} from 'node:fs';
import {replaceFile as renameSync} from './atomic_replace.mjs';
import {createHash} from 'node:crypto';
import path from 'node:path';
import sharp from 'sharp';
const encoded=new Map();
const sharedDirectory='public/textures/shared';
// A glTF round trip embeds already-delivered maps. Keep those bytes instead
// of introducing a further JPEG generation each time the geometry is edited.
const previousMaps=new Map();
if(existsSync(sharedDirectory))for(const name of readdirSync(sharedDirectory)){
 if(!/^[a-f0-9]{64}\.(jpg|png|webp)\.json$/.test(name))continue;
 const file=sharedDirectory+'/'+name.slice(0,-5),origin=JSON.parse(readFileSync(sharedDirectory+'/'+name,'utf8'));
 if(!existsSync(file))continue;
 const pixels=readFileSync(file),sha=createHash('sha256').update(pixels).digest('hex');
 if(sha!==origin.sha256)throw Error('Shared image provenance hash mismatch: '+file);
 const extension=path.extname(file).slice(1),item={pixels,extension,mimeType:extension==='jpg'?'image/jpeg':extension==='png'?'image/png':'image/webp',origin};
 previousMaps.set(sha,item);
 if(origin.sourcePixelSha256)previousMaps.set(origin.sourcePixelSha256+'|'+origin.sourceMap,item);
}
export async function shareTextures(file,outputFile=file){
 const input=readFileSync(file),jsonSize=input.readUInt32LE(12),doc=JSON.parse(input.subarray(20,20+jsonSize).toString());
 if(!doc.images?.some(image=>image.bufferView!==undefined)){if(outputFile!==file)writeFileSync(outputFile,input);return}
 const binStart=20+jsonSize+8,bin=input.subarray(binStart),imageViews=new Set();
 const focalImages=new Map((doc.materials??[]).filter(m=>m.name?.startsWith('botanical_')&&m.pbrMetallicRoughness?.baseColorTexture).map(m=>[doc.textures[m.pbrMetallicRoughness.baseColorTexture.index].source,m.name.slice('botanical_'.length)]));
 mkdirSync('public/textures/shared',{recursive:true});
 for(const [imageIndex,image] of doc.images.entries()){
  if(image.bufferView===undefined)continue;
  const view=doc.bufferViews[image.bufferView],source=bin.subarray(view.byteOffset??0,(view.byteOffset??0)+view.byteLength),key=createHash('sha256').update(source).digest('hex');
  if(!encoded.has(key)){
   const metadata=await sharp(source).metadata();
   const alpha=metadata.hasAlpha&&(await sharp(source).stats()).channels.at(-1).min<255;
   let pipeline=sharp(source);
   const baked=image.name?.startsWith('Baked_'),quality=baked?80:83;
   const prior=previousMaps.get(key)??previousMaps.get(key+'|'+image.name);
   if(prior){
    const size=await sharp(prior.pixels).metadata();
    const limit=baked?(image.name==='Baked_Mobile_landscape'?1024:512):/nor_gl|_rough|_arm/.test(image.name??'')?512:Infinity;
    if(size.width<=limit)encoded.set(key,{...prior,quality});
   }
   if(!baked&&/nor_gl|_rough|_arm/.test(image.name??''))pipeline=pipeline.resize({width:512,withoutEnlargement:true});
   if(baked)pipeline=pipeline.resize({width:image.name==='Baked_Mobile_landscape'?1024:512,withoutEnlargement:true});
   if(!encoded.has(key))encoded.set(key,{pixels:alpha?await pipeline.png({compressionLevel:9}).toBuffer():await pipeline.jpeg({quality,mozjpeg:true}).toBuffer(),extension:alpha?'png':'jpg',mimeType:alpha?'image/png':'image/jpeg',quality});
  }
  const {pixels,extension,mimeType,quality}=encoded.get(key);image.mimeType=mimeType;
  const hash=createHash('sha256').update(pixels).digest('hex'),target='public/textures/shared/'+hash+'.'+extension;
  if(!existsSync(target)){writeFileSync(target+'.next',pixels);renameSync(target+'.next',target)}
  let origin={origin:'Blender-exported '+image.name+' material map. '+(image.name?.startsWith('Baked_')?'Cycles emission bake of authored architectural geometry, source material colors and geometric contact occlusion; not an AI image. ':'Derived from CC0 Poly Haven sources; Craft swatches are baked by Blender; physical scales and processing are in config/craft.materials.json and its current revision manifest in assets/processed. ')+'Source licenses and processing are recorded in assets/manifest.json. '+(extension==='jpg'?'Opaque pixels encoded as JPEG at quality '+quality+'.':'Source leaf transparency preserved in PNG.')+' Shared locally across scene partitions.',sourceMap:image.name,sourcePixelSha256:key,sha256:hash};
  if(focalImages.has(imageIndex)){
   const authoredFile='assets/processed/focal-r12-fix2/'+focalImages.get(imageIndex)+'.png';
   origin.origin='Locally authored botanical material swatch generated by scripts/bake_focal_foliage.py; source '+authoredFile+'. Veins, midrib and age variation are deterministic artistic interpretation, not Poly Haven source material or a garden image. Source provenance is in assets/processed/focal-r12-fix2/manifest.json. Opaque delivery encoded as JPEG quality '+quality+'.';
   origin.authoredSourceFile=authoredFile;origin.authoredSourceSha256=createHash('sha256').update(readFileSync(authoredFile)).digest('hex');
  }
  origin.prompt=origin.origin;
  if(encoded.get(key).origin)origin=encoded.get(key).origin;
  writeFileSync(target+'.json.next',JSON.stringify(origin,null,2));renameSync(target+'.json.next',target+'.json');
  imageViews.add(image.bufferView);delete image.bufferView;image.uri=path.relative(path.dirname(file),target).replaceAll('\\','/');
 }
 const used=new Set();
 function scan(value){if(!value||typeof value!=='object')return;for(const [k,v]of Object.entries(value)){if(k==='bufferView')used.add(v);else scan(v)}}
 scan(doc);for(const index of used)imageViews.delete(index);
 const remap=new Map(),views=[],chunks=[];let offset=0;
 for(const [index,view]of doc.bufferViews.entries()){
  if(imageViews.has(index))continue;
  const data=bin.subarray(view.byteOffset??0,(view.byteOffset??0)+view.byteLength);const padding=(4-data.length%4)%4;
  remap.set(index,views.length);views.push({...view,byteOffset:offset});chunks.push(data,Buffer.alloc(padding));offset+=data.length+padding;
 }
 function rewrite(value){if(!value||typeof value!=='object')return;for(const [k,v]of Object.entries(value)){if(k==='bufferView')value[k]=remap.get(v);else rewrite(v)}}
 rewrite(doc);doc.bufferViews=views;doc.buffers=[{byteLength:offset}];
 let json=Buffer.from(JSON.stringify(doc));json=Buffer.concat([json,Buffer.alloc((4-json.length%4)%4,0x20)]);
 const header=Buffer.alloc(20),binaryHeader=Buffer.alloc(8);header.writeUInt32LE(0x46546c67);header.writeUInt32LE(2,4);header.writeUInt32LE(28+json.length+offset,8);header.writeUInt32LE(json.length,12);header.writeUInt32LE(0x4e4f534a,16);binaryHeader.writeUInt32LE(offset);binaryHeader.writeUInt32LE(0x004e4942,4);
 writeFileSync(outputFile+'.shared.glb',Buffer.concat([header,json,binaryHeader,...chunks]));renameSync(outputFile+'.shared.glb',outputFile);
}
