import {toolAction} from './ui_navigation.mjs';
// Browser acceptance of the shipped feature. No model calls or mocked pass claims.
import {chromium} from 'playwright';
import {mkdirSync, writeFileSync} from 'node:fs';
const base=process.env.APP_URL||'http://127.0.0.1:4291/';
const output=process.env.STORY_REPORT_DIR||'.impeccable/review/story-final';
mkdirSync(output,{recursive:true});
const report={version:'literary-comics-20260917-v4',at:new Date().toISOString(),url:base,checks:[],screenshots:[],errors:[],comicResponses:[],failed:[]};
const ip=process.env.APP_RESOLVE_IP;
const http1=process.env.GARDEN_BROWSER_HTTP1==='1';
const browser=await chromium.launch({channel:process.env.GARDEN_BROWSER_CHANNEL??'chromium',headless:true,args:[...(ip?[`--host-resolver-rules=MAP ${new URL(base).hostname} ${ip}`,'--no-proxy-server','--disable-quic']:[]),...(http1?['--disable-http2']:[])]});
const page=await browser.newPage({viewport:{width:1440,height:900}});
page.setDefaultTimeout(30000);
page.on('pageerror',e=>report.errors.push(e.message));
page.on('response',r=>{if(r.url().includes('/comics/'))report.comicResponses.push({url:r.url(),status:r.status()});if(r.status()>=400&&!r.url().endsWith('favicon.ico'))report.failed.push({url:r.url(),status:r.status()});});
const check=(ok,label)=>{if(!ok)throw new Error(label);report.checks.push(label);console.log('PASS '+label);};
const button=name=>page.getByRole('button',{name,exact:true});
const lib=()=>page.locator('.story-library');
const comic=()=>page.locator('.motion-comic');
const chooseVersion=id=>lib().getByRole('combobox',{name:'剧情依据版本',exact:true}).selectOption(id);
const journal=()=>page.evaluate(()=>{const id=localStorage.getItem('daguanyuan.edition.v1')||'original80',key='daguanyuan.simulation.v1'+(id==='original80'?'':'.'+id);return JSON.parse(localStorage.getItem(key));});
const world=j=>j[j.active].snapshots[j[j.active].cursor].worldState;
const shot=async name=>{if(name!=='failure')await page.waitForFunction(()=>{const im=document.querySelector('.motion-comic img')??document.querySelector('.story-preview img');return !im||(im.complete&&im.naturalWidth>0);});await page.waitForTimeout(200);const path=`${output}/${name}.png`;await page.screenshot({path});report.screenshots.push(path);};
const ready=()=>page.waitForFunction(()=>{const im=document.querySelector('.motion-comic img');return im?.complete&&im.naturalWidth>0;});
try {
 await page.goto(base);await page.locator('.workspace-more > summary').waitFor();await toolAction(page, '剧情画卷');
 check(await lib().getByRole('combobox',{name:'剧情依据版本'}).inputValue()==='original80','eighty chapters is the default for a fresh visitor');
 check(await lib().locator('.story-chapters>button').count()===3,'eighty-chapter catalog excludes continuations');
 await shot('desktop-library');await button('展开动态漫画').click();await ready();await button('暂停漫画').click();
 await page.waitForFunction(()=>document.querySelector('.motion-comic')?.classList.contains('is-paused')&&getComputedStyle(document.querySelector('.comic-art img')).animationPlayState==='paused');
 const frozen=await comic().locator('img').evaluate(e=>({scale:getComputedStyle(e).scale,transform:getComputedStyle(e).transform}));await page.waitForTimeout(350);
 check(JSON.stringify(frozen)===JSON.stringify(await comic().locator('img').evaluate(e=>({scale:getComputedStyle(e).scale,transform:getComputedStyle(e).transform}))),'pause freezes the illustration');
 await button('下一镜').click();check(await comic().getByRole('button',{name:'第2镜：惜春'}).getAttribute('aria-pressed')==='true','manual second panel is selected');
 await button('重播漫画').click();await page.waitForFunction(()=>document.querySelectorAll('.comic-timeline button')[2]?.getAttribute('aria-pressed')==='true');await button('暂停漫画').click();
 check(await comic().locator('.comic-timeline button').nth(2).getAttribute('aria-pressed')==='true','pause after automatic arrival preserves the final panel');
 await button('播放漫画').click();check(await comic().locator('.comic-timeline button').nth(0).getAttribute('aria-pressed')==='true','explicit play from the ended panel restarts the comic');await button('下一镜').click();
 await shot('desktop-comic');await page.keyboard.press('Escape');check(await comic().count()===0&&await lib().isVisible(),'Escape closes only the comic and returns to its library');
 await chooseVersion('cheng120');check(await lib().getByRole('button',{name:/第 97 回 焚稿断痴情/}).count()===1,'Cheng continuation exposes chapter 97');
 await lib().getByRole('button',{name:/第 97 回 焚稿断痴情/}).click();await button('从此幕入局').click();await ready();
 check(world(await journal()).storyNodeId==='manuscript-97'&&world(await journal()).editionId==='cheng120','entering chapter 97 saves the selected literary branch');
 await button('暂停漫画').click();await shot('cheng-comic');await button('回到园中').click();
 check(await page.getByLabel('世界推演控制台').isVisible(),'comic returns to the simulation');
 const original=await journal();await toolAction(page, '剧情画卷');await chooseVersion('guiyou108');
 check(await lib().getByRole('button',{name:/第 97 回/}).count()===0,'Guiyou does not borrow the Cheng chapter');
 await lib().getByRole('button',{name:/第 90 回 春日待好姻/}).click();await button('从此幕入局').click();await ready();await button('关闭动态漫画').click();
 check(world(await journal()).storyNodeId==='hope-90','Guiyou has its own starting memory and node');
 await toolAction(page, '剧情画卷');await chooseVersion('cheng120');check(JSON.stringify(await journal())===JSON.stringify(original),'switching back preserves the exact original Cheng journal');
 await chooseVersion('guiyou108');await button('关闭剧情画卷').click();await page.reload();await page.locator('.workspace-more > summary').waitFor();
 await toolAction(page, '剧情画卷');check(await lib().getByRole('combobox',{name:'剧情依据版本'}).inputValue()==='guiyou108'&&world(await journal()).storyNodeId==='hope-90','reload preserves edition and story branch');
 await button('关闭剧情画卷').click();await toolAction(page, '游园设置');await page.getByLabel('避免剧透',{exact:true}).check();await page.getByRole('slider',{name:'阅读进度'}).fill('40');await button('关闭设置').click();await toolAction(page, '剧情画卷');
 check(await lib().locator('.story-chapters>button').count()===2,'spoiler setting hides all later nodes');
 await button('关闭剧情画卷').click();await toolAction(page, '游园设置');await page.getByLabel('避免剧透',{exact:true}).uncheck();await button('关闭设置').click();
 await page.setViewportSize({width:390,height:844});await toolAction(page, '剧情画卷');await lib().getByRole('combobox',{name:'选择剧情节点'}).selectOption('poems-82');
 await lib().evaluate(e=>e.scrollTop=0);await shot('mobile-library');await button('展开动态漫画').click();await ready();await button('暂停漫画').click();await shot('mobile-comic');
 check(await comic().evaluate(e=>e.scrollWidth<=innerWidth),'390px comic has no horizontal overflow');
 const imageUrl=await comic().locator('img').evaluate(e=>e.currentSrc);check(imageUrl.endsWith('/bamboo.webp'),'phone uses the full-resolution comic while previews stay small');
 await page.setViewportSize({width:320,height:720});await shot('compact-comic');
 check(await comic().getByRole('button',{name:'下一镜'}).evaluate(e=>{const b=e.getBoundingClientRect();return b.height>=44&&b.width>=44&&b.left>=0&&b.right<=innerWidth;}),'320px playback controls stay on screen and touch sized');
 await page.emulateMedia({reducedMotion:'reduce'});check(await comic().locator('img').evaluate(e=>getComputedStyle(e).animationName)==='none','reduced motion removes spatial animation');
 await button('下一镜').click();check(await comic().getByRole('button',{name:'第2镜：独吟'}).getAttribute('aria-pressed')==='true','static mode still supports panel navigation');
 await button('关闭动态漫画').click();await lib().evaluate(e=>e.scrollTop=0);await shot('compact-library');
 check(await lib().evaluate(e=>e.scrollWidth<=e.clientWidth+1),'320px library has no horizontal overflow');
 await button('关闭剧情画卷').click();await page.locator('.workspace-more > summary').click();check(await button('剧情画卷').isVisible(),'mobile story entry remains reachable from More after closing dialogs');
 check(report.errors.length===0,'no browser runtime errors');check(report.failed.length===0,'no failed feature resources');
 report.passed=true;
} catch(e){report.passed=false;report.failure=String(e);await shot('failure');process.exitCode=1;}
finally {writeFileSync(`${output}/report.json`,JSON.stringify(report,null,2));await browser.close();}
