import {readFileSync,writeFileSync,existsSync,readdirSync,mkdirSync,statSync,renameSync} from 'node:fs';
import path from 'node:path';
import {createHash} from 'node:crypto';
import {z} from 'zod';
const read=p=>JSON.parse(readFileSync(p,'utf8'));const hash=p=>createHash('sha256').update(readFileSync(p)).digest('hex');
const write=(p,value)=>{writeFileSync(p+'.next',value);renameSync(p+'.next',p)};
const names=['places','characters','events','sources','relations','routes'];const d=Object.fromEntries(names.map(n=>[n,read(`data/canon/${n}.json`)]));
const refs=z.array(z.string()).min(1);const ids=z.string().min(1);const ch=z.number().int().min(1).max(120);
const schemas={places:z.object({id:ids,name:ids,aliases:z.array(z.string()),description:ids,sourceRefs:refs,spatialInterpretation:z.literal('interpretive')}),characters:z.object({id:ids,name:ids,shortBio:ids,sourceRefs:refs,introductionChapter:ch,residencies:z.array(z.object({placeId:ids,fromChapter:ch,toChapter:ch.nullable(),sourceRefs:refs}))}),events:z.object({id:ids,title:ids,chapter:ch,summary:ids,characterIds:z.array(ids).min(1),canonicalPlaceId:ids.nullable(),displayPlaceId:ids.nullable(),locationCertainty:z.enum(['explicit','display_only','residency_inference']),sourceRefs:refs,contentType:z.literal('canonical'),reviewStatus:z.literal('source_checked')}),sources:z.object({id:ids,title:ids,url:z.url(),rawSha256:z.string().length(64),normalizedTextSha256:z.string().length(64),paragraphIndex:z.number().int().min(0),evidenceExcerpt:ids,chapter:ch,reviewStatus:z.literal('source_checked')}),routes:z.object({id:ids,title:ids,orderedStops:z.array(ids).min(2),eventIds:refs,pathNodeIds:z.array(ids).min(2),routeType:z.literal('interpretive'),sourceRefs:refs}),relations:z.object({fromId:ids,toId:ids,relationType:ids,sourceRefs:refs})};
const checks=[];const assert=(value,message)=>{if(!value)throw Error(message);checks.push(message)};
for(const n of names){z.array(schemas[n]).parse(d[n]);if(n!=='relations')assert(new Set(d[n].map(x=>x.id)).size===d[n].length,n+' unique IDs')}
const places=new Set(d.places.map(x=>x.id)),chars=new Set(d.characters.map(x=>x.id)),sources=new Set(d.sources.map(x=>x.id)),events=new Set(d.events.map(x=>x.id));
assert(places.size===15,'15 places including the three reference additions');assert(chars.size>=12,'at least 12 characters');assert(events.size>=16,'at least 16 events');assert(new Set(d.events.map(x=>x.chapter)).size>=8,'at least 8 chapters');assert(d.routes.length===3,'3 planned routes');
for(const name of names.filter(n=>n!=='sources'))for(const obj of d[name])for(const ref of obj.sourceRefs)assert(sources.has(ref),'source foreign key '+ref);
for(const e of d.events){assert(e.characterIds.every(id=>chars.has(id)),'event character keys '+e.id);assert([e.canonicalPlaceId,e.displayPlaceId].every(id=>id===null||places.has(id)),'event place keys '+e.id);assert(e.locationCertainty!=='display_only'||e.canonicalPlaceId===null,'display location honest '+e.id)}
for(const c of d.characters)for(const r of c.residencies){assert(places.has(r.placeId),'residency place '+c.id);assert(r.sourceRefs.every(id=>sources.has(id)),'residency sources '+c.id)}
for(const r of d.relations)assert(chars.has(r.fromId)&&chars.has(r.toId),'relation keys');
for(const s of d.sources){const prefix=`data/raw/chapter-${String(s.chapter).padStart(3,'0')}`,raw=read(prefix+'.json');assert(s.rawSha256===hash(prefix+'.html'),'raw SHA256 '+s.id);assert(s.normalizedTextSha256===hash(prefix+'.txt'),'normalized SHA256 '+s.id);assert(raw.paragraphs[s.paragraphIndex].includes(s.evidenceExcerpt),'evidence located '+s.id)}
const m=read('public/scene-manifest.json');assert(m.places.length===places.size&&m.places.every(p=>places.has(p.id)),'manifest matches canon places');
const pathIDs=new Set(m.pathNodes.map(n=>n.id)),edgeKeys=new Set(m.pathEdges.flatMap(e=>[e.from+'|'+e.to,e.to+'|'+e.from]));
const gardenBounds=read('reports/acceptance/model-optimization.json').find(x=>x.file==='public/models/overview.glb').bounds;
assert(m.pathNodes.every(n=>(n.position[0]/(gardenBounds.max[0]-1.5))**2+(n.position[2]/(gardenBounds.max[2]-1.5))**2<1),'all route nodes and road margins supported by garden base');
for(const r of d.routes){assert(r.orderedStops.every(id=>places.has(id))&&r.eventIds.every(id=>events.has(id)),'route foreign keys '+r.id);assert(r.pathNodeIds.every(id=>pathIDs.has(id)),'route path nodes '+r.id);assert(r.pathNodeIds.slice(1).every((id,i)=>edgeKeys.has(r.pathNodeIds[i]+'|'+id)),'route uses connected edges '+r.id)}
function glbJSON(file){const b=readFileSync(file);assert(b.subarray(0,4).toString()==='glTF','GLB magic '+file);assert(b.readUInt32LE(8)===b.length,'GLB size '+file);const length=b.readUInt32LE(12);return JSON.parse(b.subarray(20,20+length).toString())}
const overview=glbJSON('public/models/overview.glb');
const low=glbJSON('public/models/overview-low.glb');
for(const p of m.places)assert(low.nodes.some(n=>n.extras?.placeId===p.id),'low overview place '+p.id);
for(const p of m.places){const mobile=glbJSON('public/'+p.mobileModel);assert(mobile.nodes.some(n=>n.extras?.placeId===p.id),'mobile partition place '+p.id);assert(p.hotspots.every(h=>mobile.nodes.some(n=>n.extras?.hotspotId===h.id)),'mobile partition hotspots '+p.id);assert(mobile.extensionsUsed?.includes('KHR_draco_mesh_compression'),'mobile partition compressed '+p.id)}
for(const p of d.places)for(const f of p.features??[])assert(f.sourceRefs.every(id=>sources.has(id)),'architectural feature sources '+p.id);
for(const p of m.places){assert(overview.nodes.some(n=>n.extras?.placeId===p.id),'overview extras '+p.id);const part=glbJSON('public/'+p.model);assert(part.nodes.some(n=>n.extras?.placeId===p.id),'partition extras '+p.id);for(const h of p.hotspots){const node=part.nodes.find(n=>n.extras?.hotspotId===h.id);assert(!!node,'hotspot exported '+h.id);assert(h.position.every((v,i)=>Math.abs(v-(node.translation?.[i]??0))<.001),'hotspot coordinate conversion '+h.id)}const root=part.nodes.find(n=>n.extras?.entityType==='place');assert(!root.translation||root.translation.every(v=>v===0),'partition origin identity '+p.id)}
const assets=read('assets/manifest.json');for(const a of assets.filter(a=>a.status==='approved')){assert(existsSync(a.licenseEvidencePath),'license '+a.assetId);assert(hash(a.sourceFile)===a.sourceSha256,'asset hash '+a.assetId);for(const dep of a.dependencies??[])assert(hash(dep.file)===dep.sha256,'asset dependency '+dep.file)}
for(const a of assets.filter(a=>a.status==='approved'))for(const [i,file]of (a.derivativeFiles??[]).entries())assert(hash(file)===a.derivativeSha256[i],'derivative hash '+file);
const walk=p=>readdirSync(p,{withFileTypes:true}).flatMap(e=>e.isDirectory()?walk(p+'/'+e.name):[p+'/'+e.name]);
assert(walk('public').every(f=>/^(public\/models\/.*\.glb|public\/data\/(places|characters|events|sources|routes|relations)\.json|public\/scene-manifest\.json|public\/textures\/.*\.(jpg|png|webp|hdr|json)|public\/art\/[a-z0-9-]+\.(webp|json|webp\.json)|public\/draco\/(draco_decoder.js|draco_decoder.wasm|draco_wasm_wrapper.js|LICENSE|AUTHORS))$/.test(f)),'public file allowlist');
for(const result of read('reports/acceptance/model-optimization.json')){
 assert(hash(result.file)===result.sha256,'optimized model hash '+result.file);
 for(const img of glbJSON(result.file).images??[]){if(img.bufferView!==undefined)continue;assert(!!img.uri&&!/^(https?:|data:|\/)/.test(img.uri),'local model texture '+result.file);const target=path.resolve(path.dirname(result.file),img.uri);assert(target.startsWith(path.resolve('public/textures/shared')+path.sep)&&existsSync(target),'shared texture exists '+img.uri);assert(hash(target)===path.basename(target).split('.')[0],'shared texture content hash '+img.uri)}
}
const art=read('public/art/manifest.json');assert(art.length===15,'15 approved visual references');for(const image of art){assert(image.placeId===null||places.has(image.placeId),'image links to a real destination '+image.id);assert(hash('public/'+image.url)===image.sha256,'published reference hash '+image.id);assert(image.prompt.length>100,'reference prompt provenance '+image.id)}
assert(!existsSync('public/data/raw')&&!existsSync('public/data/pending'),'private raw and pending excluded');
if(process.argv.includes('--publish')){mkdirSync('public/data',{recursive:true});for(const n of names)write(`public/data/${n}.json`,JSON.stringify(d[n]));}
const allGLB=walk('public/models').filter(f=>f.endsWith('.glb'));const report={timestamp:new Date().toISOString(),passed:checks.length,checks,modelBytes:allGLB.reduce((sum,f)=>sum+statSync(f).size,0),overviewBytes:statSync('public/models/overview.glb').size,counts:Object.fromEntries(names.map(n=>[n,d[n].length]))};write('reports/acceptance/integrity.json',JSON.stringify(report,null,2));console.log('PASS',checks.length,'integrity checks.',report.counts);
