import WorkspaceHeader from './panels/WorkspaceHeader';
import Disclosure from './panels/Disclosure';
import SceneBoundary from './panels/SceneBoundary';
import gardenMark from './assets/garden-mark.svg?no-inline';
import StoryExperience from './panels/StoryExperience';
import DreamExperience from './panels/DreamExperience';
import SimulationPanel from './panels/SimulationPanel';
import SimulationStage from './panels/SimulationStage';
import {useSimulation} from './simulation/store';
import {waterMapPath} from './data/waterMapPath';
import {AtmosphereControl,PlaceReference,ReferenceGallery,ViewControls} from './panels/ReferenceExperience';
import {useEffect,useRef,useState,lazy,Suspense} from 'react';
import {BookOpen,Compass,MapPin,ArrowUpRight,ArrowLeft,ArrowRight,ChevronLeft,ChevronRight,Search,X,Home,Play,Pause,Route as RouteIcon,PanelLeftClose,PanelLeftOpen,Eye,VolumeX,RotateCcw,Maximize,SlidersHorizontal} from 'lucide-react';
import {useGarden,relatedPlaces} from './state/store';
import {LocalCanonProvider} from './providers/LocalCanonProvider';
import type {CanonEvent,Source} from './data/types';
const GardenScene=lazy(()=>import('./scene/GardenScene'));
const CHINESE:Record<number,string>={17:'十七',18:'十八',23:'二十三',26:'二十六',27:'二十七',37:'三十七',38:'三十八',40:'四十',41:'四十一',50:'五十',63:'六十三',74:'七十四',76:'七十六'};
const chapterLabel=(n:number)=>`第${CHINESE[n]??n}回`;
function IconButton({label,onClick,children,active}:{label:string;onClick:()=>void;children:React.ReactNode;active?:boolean}){return <button className={'icon-button '+(active?'active':'')} onClick={onClick} aria-label={label} aria-pressed={active} title={label}>{children}</button>}
function Sources({refs}:{refs:string[]}){const state=useGarden();return <div className="source-list">{refs.map(id=>{const s=state.data?.sources.find(s=>s.id===id);if(!s||state.spoilerLimit!==null&&s.chapter>state.spoilerLimit)return null;return <details key={id}><summary><BookOpen size={14}/>{s.title}<ChevronRight size={14}/></summary><div className="source-body"><blockquote>{s.evidenceExcerpt}</blockquote><p>{s.paragraphLocator} · 已查阅来源</p><a href={s.url+(s.revisionId?`?oldid=${s.revisionId}`:'')} target="_blank" rel="noreferrer">查看原文与上下文 <ArrowUpRight size={13}/></a></div></details>})}</div>}
function EventRow({event}:{event:CanonEvent}){const s=useGarden();return <button className={'event-row '+(s.selectedEventId===event.id?'selected':'')} onClick={()=>s.chooseEvent(event)}><span>{chapterLabel(event.chapter)}</span><strong>{event.title}</strong><ArrowUpRight size={15}/></button>}
function Index(){const s=useGarden();const [query,setQuery]=useState('');const data=s.data!;const visible=LocalCanonProvider.visibleEvents(data.events,s.spoilerLimit);const chapters=[...new Set(visible.map(e=>e.chapter))].sort((a,b)=>a-b);const associations=relatedPlaces(data,s.selectedCharacterId,s.selectedChapter,s.spoilerLimit);const input=useRef<HTMLInputElement>(null);
 useEffect(()=>{setQuery('')},[s.tab]);
 return <aside className={'index '+(s.indexOpen?'open':'closed')} aria-label="园林内容索引">
 <div className="index-heading"><h2>{s.tab==='places'?'园中景致':s.tab==='characters'?'园中人物':'回目拾遗'}</h2><IconButton label="收起索引" onClick={()=>useGarden.setState({indexOpen:false})}><PanelLeftClose size={17}/></IconButton></div>
 <div className="index-tabs" role="tablist" aria-label="索引分类">{[['places','地点'],['characters','人物'],['chapters','回目']].map(([tab,label])=><button role="tab" aria-selected={s.tab===tab} key={tab} onClick={()=>useGarden.setState({tab:tab as typeof s.tab})}>{label}</button>)}</div>
 <label className="search"><Search size={15}/><input ref={input} aria-label="搜索园中内容" placeholder={s.tab==='places'?'寻一处园景…':s.tab==='characters'?'寻一位故人…':'搜索回目或情节…'} value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<button aria-label="清空搜索" onClick={()=>{setQuery('');input.current?.focus()}}><X size={13}/></button>}</label>
 <div className="index-scroll">
 {s.tab==='places'&&<div className="place-list">{data.places.filter(p=>[p.name,...p.aliases,p.theme].some(t=>t.includes(query))).map(p=>{const index=data.places.indexOf(p);return <button key={p.id} className={'place-row '+(s.selectedPlaceId===p.id?'selected':'')+((s.selectedCharacterId||s.selectedChapter)&&associations.includes(p.id)?' associated':'')} onClick={()=>s.choosePlace(p.id)}><span className="place-number">{String(index+1).padStart(2,'0')}</span><span><strong>{p.name}</strong><small>{p.theme}{data.manifest.places.find(x=>x.id===p.id)?.featured?' · 院落细览':''}</small></span><ChevronRight size={14}/></button>})}</div>}
 {s.tab==='places'&&<div className="place-list">{data.manifest.architecturalScenes?.filter(p=>[p.name,p.character].some(t=>t.includes(query))).map(p=><button key={p.id} className={'place-row architectural-scene '+(s.architecturalFocusId===p.id?'selected':'')} onClick={()=>s.focusArchitecture(p.id)}><span className="place-number">景</span><span><strong>{p.name}</strong><small>{p.character}</small></span><ChevronRight size={14}/></button>)}</div>}
 {s.tab==='characters'&&<div className="character-list">{data.characters.filter(c=>[c.name,...c.aliases].some(t=>t.includes(query))).map(c=><button key={c.id} className={s.selectedCharacterId===c.id?'selected':''} onClick={()=>s.chooseCharacter(c.id)}><span className="character-seal">{c.name.slice(-1)}</span><span><strong>{c.name}</strong><small>{s.spoilerLimit!==null&&c.introductionChapter>s.spoilerLimit?'资料尚未解锁':s.spoilerLimit!==null&&s.spoilerLimit<37?'原著人物':c.aliases[0]??'原著人物'}</small></span><ChevronRight size={14}/></button>)}</div>}
 {s.tab==='chapters'&&<div className="chapter-list">{chapters.filter(ch=>String(ch).includes(query)||chapterLabel(ch).includes(query)||visible.some(e=>e.chapter===ch&&e.title.includes(query))).map(ch=><button key={ch} onClick={()=>s.chooseChapter(ch)} className={s.selectedChapter===ch?'selected':''}><BookOpen size={16}/><span><strong>{chapterLabel(ch)}</strong><small>{visible.find(e=>e.chapter===ch)?.title.split(' · ')[0]}</small></span><span>{visible.filter(e=>e.chapter===ch).length}</span></button>)}</div>}
 {((s.tab==='places'&&!data.places.some(p=>[p.name,...p.aliases,p.theme].some(t=>t.includes(query)))&&!data.manifest.architecturalScenes?.some(p=>[p.name,p.character].some(t=>t.includes(query))))||(s.tab==='characters'&&!data.characters.some(c=>[c.name,...c.aliases].some(t=>t.includes(query))))||(s.tab==='chapters'&&!chapters.some(ch=>String(ch).includes(query)||chapterLabel(ch).includes(query)||visible.some(e=>e.chapter===ch&&e.title.includes(query)))))&&<p className="empty">未找到“{query}”。试试地点、姓名或回目数字。</p>}
 </div><div className="index-footer"><span className="seal-small">梦</span><p>循景入书，因人见园。<small>文学空间再现 · 非唯一考据复原</small></p></div>
 </aside>;
}
function DetailPanel(){const s=useGarden(),data=s.data!;const event=data.events.find(e=>e.id===s.selectedEventId);const person=data.characters.find(c=>c.id===s.selectedCharacterId);const place=data.places.find(p=>p.id===s.selectedPlaceId);const events=LocalCanonProvider.visibleEvents(data.events,s.spoilerLimit).filter(e=>person?e.characterIds.includes(person.id):s.selectedChapter!==null&&!place?e.chapter===s.selectedChapter:place?e.displayPlaceId===place.id:false);const relationPlaces=relatedPlaces(data,person?.id??null,s.selectedChapter,s.spoilerLimit);const related=place?[...new Set([...data.characters.filter(c=>c.residencies.some(r=>r.placeId===place.id&&(s.spoilerLimit===null||r.fromChapter<=s.spoilerLimit))).map(c=>c.id),...events.flatMap(e=>e.characterIds)])]:event?.characterIds??[];const hotspot=data.manifest.places.find(p=>p.id===place?.id)?.hotspots.find(h=>h.id===s.hotspotId);
 if(!s.panelOpen)return null;
 const title=event?.title.split(' · ')[0]??person?.name??place?.name??(s.selectedChapter!==null?chapterLabel(s.selectedChapter):'园中拾遗');
 return <aside className="detail-panel" aria-label="选中内容详情" data-testid="detail-panel"><div className="drawer-handle"/><div className="detail-top"><IconButton label="关闭详情" onClick={()=>useGarden.setState({panelOpen:false})}><X size={19}/></IconButton></div><div className="detail-scroll"><h2>{title}</h2>
 {event?<><div className="detail-subtitle">{chapterLabel(event.chapter)}<span>已查阅来源</span></div><p className="detail-prose">{event.summary}</p><div className="place-context"><MapPin size={16}/><span>{event.locationCertainty==='display_only'?'展示位置':event.locationCertainty==='residency_inference'?'依居所推定':'原著地点'}：{place?.name??'未确定'}</span></div>{event.locationCertainty==='display_only'&&<p className="note">此场景用于阅读联动，原著发生地点见摘要。</p>}<h3>相关人物</h3><div className="people-chips">{event.characterIds.map(id=><button key={id} onClick={()=>s.chooseCharacter(id)}>{data.characters.find(c=>c.id===id)?.name}</button>)}</div><h3>原文依据</h3><Sources refs={event.sourceRefs}/><button className="text-button" onClick={()=>s.chooseChapter(event.chapter)}>查看本回其他情节 <ArrowRight size={15}/></button></>:
 person?<><div className="detail-subtitle">{s.spoilerLimit!==null&&s.spoilerLimit<37?'《红楼梦》人物':person.aliases.join(' · ')||'《红楼梦》人物'}</div><p className="detail-prose">{s.spoilerLimit!==null&&person.introductionChapter>s.spoilerLimit?`人物资料在第${person.introductionChapter}回解锁。可调整阅读进度后查看。`:person.shortBio}</p><h3>与园景的联系</h3><p className="note">居所与事件关联，不表示人物此刻在场。</p><div className="related-places">{relationPlaces.map(id=><button key={id} onClick={()=>s.choosePlace(id)}><MapPin size={14}/>{data.places.find(p=>p.id===id)?.name}<ArrowUpRight size={14}/></button>)}{!relationPlaces.length&&<p className="empty">当前阅读进度内，暂无已核实的地点关联。</p>}</div>{data.relations.filter(r=>(r.fromId===person.id||r.toId===person.id)&&(s.spoilerLimit===null||r.validity.fromChapter<=s.spoilerLimit)).map(r=><div className="relation" key={r.label}><p>{r.label}：{data.characters.find(c=>c.id===(r.fromId===person.id?r.toId:r.fromId))?.name}</p><Sources refs={r.sourceRefs}/></div>)}<h3>相关情节 <span>{events.length}</span></h3>{events.map(e=><EventRow key={e.id} event={e}/>)}<h3>人物依据</h3><Sources refs={person.sourceRefs}/></>:
 place?<><ViewControls/><PlaceReference placeId={place.id}/><div className="detail-subtitle">{place.theme} · {place.id==='xiaoxiangguan'?'一帘竹影，几卷诗书':place.id==='yihongyuan'?'红香绿玉，院中日常':place.id==='hengwuyuan'?'蘅芷清芬，素室幽芳':place.id==='qiushuangzhai'?'疏朗书斋，海棠诗兴':'园林中的一处停留'}</div><p className="detail-prose">{s.spoilerLimit!==null&&s.spoilerLimit<({daguanyuan_gate:17,qujingtongyou:17,xiaoxiangguan:40,yihongyuan:23,hengwuyuan:40,qiushuangzhai:37,daoxiangcun:23,ouxiangxie:38,dicuiting:27,luxuean:49,tubishanzhuang:76,aojingxiguan:76}[place.id]??23)?'此处为原著文学空间的设计再现。居住与情节资料将随阅读进度开放。':place.description}</p>{hotspot&&<div className="hotspot-note"><strong>{hotspot.name}</strong><p>对应原著空间意象的设计陈设；尺寸、形制和摆位为本项目解释。</p><Sources refs={place.sourceRefs}/></div>}<div className="place-context"><Compass size={16}/><span>空间布局 · 设计解释</span></div><h3>相关人物</h3><div className="people-chips">{related.map(id=><button key={id} onClick={()=>s.chooseCharacter(id)}>{data.characters.find(c=>c.id===id)?.name}</button>)}{!related.length&&<p className="note">暂无已核实的人物关联。</p>}</div>{data.manifest.places.find(p=>p.id===place.id)?.featured&&<button className="interior-button" onClick={()=>useGarden.setState({hotspotId:s.hotspotId===place.id+'-study'?null:place.id+'-study'})}><Eye size={16}/>{s.hotspotId===place.id+'-study'?'回到完整院落':'查看屋内陈设'}</button>}<h3>此景中的故事 <span>{events.length}</span></h3>{events.length?events.map(e=><EventRow key={e.id} event={e}/>):<p className="empty">当前进度下暂无可展示的事件。</p>}{place.features?.some(f=>f.sourceRefs.some(id=>{const src=data.sources.find(x=>x.id===id);return src&&(s.spoilerLimit===null||src.chapter<=s.spoilerLimit)}))&&<><h3>原著中的形与景</h3><ul className="architecture-features">{place.features.filter(f=>f.sourceRefs.some(id=>{const src=data.sources.find(x=>x.id===id);return src&&(s.spoilerLimit===null||src.chapter<=s.spoilerLimit)})).map(f=><li key={f.text}>{f.text}</li>)}</ul><p className="note">构件关系据原文整理；尺寸、雕纹与具体摆位为设计解释。</p></>}<h3>地点来源</h3><Sources refs={place.sourceRefs}/></>:
 <><p className="detail-prose">沿着这一回的情节，在园中寻找人物与地点的交会。</p><div className="related-places">{relationPlaces.map(id=><button key={id} onClick={()=>s.choosePlace(id)}><MapPin size={14}/>{data.places.find(p=>p.id===id)?.name}<ArrowUpRight size={14}/></button>)}</div><h3>本回情节 <span>{events.length}</span></h3>{events.map(e=><EventRow key={e.id} event={e}/>)}</>}
 </div><div className="detail-footer"><BookOpen size={13}/>依据原著整理 · 摘要非逐字引文</div></aside>;
}
function MiniMap(){const s=useGarden(),m=s.data!.manifest;return <div className="minimap"><div><span>园图</span><button onClick={()=>{s.home();useGarden.setState({planView:true})}}>俯瞰 <Maximize size={11}/></button></div><svg viewBox="-156 -156 312 306" aria-label="大观园小地图"><rect x="-147" y="-147" width="294" height="284" rx="6" fill="var(--panel-secondary)"/><path d={waterMapPath(m.lake)} fill="var(--panel-hover)" fillRule="evenodd"/>{m.pathEdges.map((e,index)=>{const a=m.pathNodes.find(n=>n.id===e.from)!.position,b=m.pathNodes.find(n=>n.id===e.to)!.position;return <line key={e.from+'-'+e.to+'-'+index} x1={a[0]} y1={a[2]} x2={b[0]} y2={b[2]} stroke="var(--border)" strokeWidth="2"/>})}{m.places.map(p=><g key={p.id} role="button" tabIndex={0} aria-label={'地图选择'+p.name} onClick={()=>s.choosePlace(p.id)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();s.choosePlace(p.id)}}}><circle cx={p.position[0]} cy={p.position[2]} r="9" fill="transparent"/><circle cx={p.position[0]} cy={p.position[2]} r={s.selectedPlaceId===p.id?5:3.5} fill={s.selectedPlaceId===p.id?'var(--accent)':'var(--text-muted)'} stroke="var(--text)" strokeWidth="1.5"/><title>{p.name}</title></g>)}</svg></div>}
function TourBar(){const s=useGarden();const [chosen,setChosen]=useState('first-look');const route=s.data!.routes.find(r=>r.id===(s.tourState.routeId??chosen))!;const active=s.tourState.status!=='idle';return <footer className="tour-bar"><div className="tour-picker"><RouteIcon size={21}/><div><select aria-label="选择游园路线" id="route-select" value={route.id} disabled={active} onChange={e=>setChosen(e.target.value)}>{s.data!.routes.map(r=><option key={r.id} value={r.id}>{r.title}</option>)}</select></div></div><div className="tour-description">{active?<><strong>{s.data!.places.find(p=>p.id===route.orderedStops[s.tourState.index])?.name}</strong><span>{s.tourState.index+1} / {route.orderedStops.length} 站 · {s.tourState.status==='playing'?'沿路径游览中':'已暂停'}</span></>:<><strong>{route.description}</strong><span>{route.orderedStops.length} 处停留 · 策划路线，非原著完整行迹</span></>}</div><div className="tour-controls">{active?<><IconButton label="上一站" onClick={()=>s.tourStep(s.tourState.index-1)}><ChevronLeft size={18}/></IconButton><button className="tour-play" onClick={s.toggleTour}>{s.tourState.status==='playing'?<Pause size={15}/>:<Play size={15}/>}<span>{s.tourState.status==='playing'?'暂停':'继续'}</span></button><IconButton label="下一站" onClick={()=>s.tourStep(s.tourState.index+1)}><ChevronRight size={18}/></IconButton><IconButton label="退出导览" onClick={s.exitTour}><X size={18}/></IconButton></>:<button className="tour-play" onClick={()=>s.startTour(chosen)}><Play size={15}/>开始游园</button>}</div></footer>}
function Settings(){const s=useGarden();if(!s.settingsOpen)return null;return <section className="settings-panel" aria-label="游园设置"><div className="settings-title"><h2>游园设置</h2><IconButton label="关闭设置" onClick={()=>useGarden.setState({settingsOpen:false})}><X size={16}/></IconButton></div><label>画面精度<select aria-label="画面精度" value={s.qualityLevel} onChange={e=>useGarden.setState({qualityLevel:e.target.value as 'high'|'low'})}><option value="high">精细 · 局部院落与阴影</option><option value="low">轻量 · 更流畅</option></select></label><label className="check-row"><input type="checkbox" checked={s.labels} onChange={e=>useGarden.setState({labels:e.target.checked})}/>显示地点名签</label><label className="check-row"><input type="checkbox" checked={s.motion} onChange={e=>useGarden.setState({motion:e.target.checked})}/>水面与路径动态</label><div className="setting-divider"/><label className="check-row"><input type="checkbox" checked={s.spoilerLimit!==null} onChange={e=>s.setSpoiler(e.target.checked)}/>避免剧透</label><label>已读至第 {s.readingProgress} 回<input aria-label="阅读进度" type="range" min={1} max={120} value={s.readingProgress} onChange={e=>s.setSpoiler(s.spoilerLimit!==null,Number(e.target.value))}/></label><p className="note">开启后，仅显示阅读进度内的情节、人物资料与来源。</p><div className="sound-status"><VolumeX size={15}/><span>环境声音未启用 · 暂无音频素材</span></div></section>}
function SourcePage(){const s=useGarden();if(!s.sourcesOpen)return null;const sources=s.data!.sources.filter(x=>s.spoilerLimit===null||x.chapter<=s.spoilerLimit);const unique=Array.from(new Map(sources.map(x=>[x.chapter,x])).values());return <section className="sources-page" aria-label="来源与说明"><button className="text-button" onClick={()=>useGarden.setState({sourcesOpen:false})}><ArrowLeft size={16}/>返回园林</button><h1>景有所依，文有所出。</h1><p className="source-intro">这是一座依据《红楼梦》整理的文学空间。<br/>园林帮助阅读，原著为每一次联想提供落点。</p><div className="source-columns"><div><h2>关于这座园</h2><p>本项目的方位、尺寸、建筑形制与镜头路线均为设计解释，不是唯一考据复原，也不是实体大观园的测绘模型。</p><p>“原著地点”指已有明确原文依据的地点；“展示位置”用于承载发生在首版节点之外或尚待定位的情节。所有导览均为策划串联。</p><h2>本轮空间依据</h2><p>参考用户图文索引中的成对总平面与鸟瞰，将省亲建筑群置于中部，曲水绕行，院落以山石、院墙和曲径相接。沁芳桥亭、藕香榭三向接岸，以及凸碧与凹晶的上下关系，另据第17、18、38、76回核对。</p><p>总图采用<a href="https://www.sohu.com/a/206191725_410481" target="_blank" rel="noreferrer">《红楼梦建筑图解》所载方案</a>作为构图解释。原著并未给出完整测绘平面，绝对位置、距离和游览路径仍属设计推演。参考书图仅供研究，未复制到本网站。</p><h2>底本与核查</h2><p>采用维基文库《紅樓夢》分回数字文本，记录获取日期、页面修订号、原始与规范化文本哈希。网页存在简繁及用字混合，不宣称为权威校勘本。</p><p>本版内容由执行代理逐条查阅，状态为 source_checked；未声称经人类红学专家审定。摘要与直接引文分开显示。</p><h2>素材与署名</h2><p>本项目使用的木石纹理、草丛、蕨类与环境光素材来自 <a href="https://polyhaven.com" target="_blank" rel="noreferrer">Poly Haven</a>，资产许可为 CC0 1.0。环境光与本地灯光共同呈现材质，水面在精细模式下实时反射三维场景。具体作者、哈希与衍生记录见项目资产清单。</p><h2>孙温绘本的色彩与园林</h2><p>建筑配色、彩绘檐带和花木疏密以清代孙温《红楼梦》绘本为美术依据。朱红、石绿、群青、粉白与淡金分层使用，留出庭院、石栏和水面的轮廓。图录展示有出处的绘本原图，可与三维园景对照；院落尺寸、种植位置和同景花期属于设计转译。</p><p>绘本数字图来自 <a href="https://github.com/changren-wcr/sunwen" target="_blank" rel="noreferrer">孙温《红楼梦》绘本资料库</a>，本地保存原图与校验记录。当前八类树形、庭院花卉和古建彩绘构件为本项目建模，草丛、蕨类和部分材质保留已审核的 CC0 来源。运行时全部使用本站资源。字体使用设备系统字体。</p><p>原著为公版；数字整理依据维基文库页面的 CC BY-SA 4.0 / GFDL 声明署名。</p></div><div><h2>本版原文索引</h2><p className="note">{s.spoilerLimit!==null?'已按阅读进度隐藏后续来源。':'章节链接打开所记录修订版本。'}</p>{unique.map((source:Source)=><a className="source-chapter" key={source.chapter} href={source.url+(source.revisionId?`?oldid=${source.revisionId}`:'')} target="_blank" rel="noreferrer"><span><strong>{source.title}</strong><small>获取于 {source.retrievedAt.slice(0,10)} · 修订 {source.revisionId??'未取得'}</small></span><ArrowUpRight size={17}/></a>)}<p className="note">芦雪庵名称与形制已在第49回核对；雪日联诗地点依据第49—50回的连续场景确定。未核实的其他底本异名不进入默认数据。</p></div></div></section>}
export default function App(){const s=useGarden();const simOpen=useSimulation(state=>state.open);const simImmersive=useSimulation(state=>state.immersive);const [error,setError]=useState('');const [retry,setRetry]=useState(0);useEffect(()=>{let live=true;const controller=new AbortController();new LocalCanonProvider().load(controller.signal).then(data=>{if(live){s.setData(data);setError('')}}).catch(e=>live&&setError(e.message));return()=>{live=false;controller.abort()}},[retry]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.key==='Escape'&&!e.defaultPrevented&&!(e.target as Element).closest('dialog')){if(!useGarden.getState().settingsOpen&&!useGarden.getState().sourcesOpen&&useSimulation.getState().open)useSimulation.getState().toggle();useGarden.setState({settingsOpen:false,sourcesOpen:false,panelOpen:false});useGarden.getState().exitTour()}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[]);
 const place=s.data?.places.find(p=>p.id===s.selectedPlaceId);const scenery=s.data?.manifest.architecturalScenes?.find(p=>p.id===s.architecturalFocusId);
 if(!s.data)return <main className="boot"><img className="brand-mark" src={gardenMark} width="64" height="64" alt=""/><h1>大观园 · 入梦</h1>{error?<><p role="alert">{error}</p><button onClick={()=>setRetry(retry+1)}><RotateCcw size={16}/>重新加载资料</button></>:<p role="status">正在整理入园书页…</p>}<p><a href="./reading.html">网络较慢？先打开轻量阅读</a></p></main>;
 return <div className={"app-shell"+(simOpen?' simulation-open':'')+(simOpen&&simImmersive?' simulation-immersive':'')+(s.panelOpen&&s.selectedPlaceId&&s.tourState.status==='idle'?' reading-place':'')}><a className="skip-link" href="#garden-main">跳转到园林内容</a><WorkspaceHeader/>
 <div className="workspace">{!simOpen&&<Index/>}<main id="garden-main" className={'garden-main '+(s.panelOpen?'has-detail':'')} tabIndex={-1}>
 <SceneBoundary><Suspense fallback={<div className="loading"><h2>园林即将展开</h2><a href="./reading.html">先打开轻量阅读</a></div>}><GardenScene manifest={s.data.manifest}/></Suspense></SceneBoundary>
 <SimulationStage/>
 <div className="scene-heading">{!s.indexOpen&&<IconButton label="展开索引" onClick={()=>useGarden.setState({indexOpen:true})}><PanelLeftOpen size={18}/></IconButton>}<div><h1>{place?.name??scenery?.name??(s.selectedCharacterId?'因人，寻一方景':s.selectedChapter?'循文，重访园中':'一园山水')}</h1><p>{scenery?scenery.character:place?`${place.theme} · 点击院中数字，读一处细节`:'沿一湾曲水，走入红楼深处。'}</p></div></div>
 <div className="garden-view-tools"><IconButton label="回到全园" onClick={s.home}><Home size={18}/></IconButton><Disclosure label={<><SlidersHorizontal size={17}/><span>视图</span></>}><AtmosphereControl/><button aria-label="切换地点名签" aria-pressed={s.labels} onClick={()=>useGarden.setState({labels:!s.labels})}><MapPin size={16}/>地点名签</button><button aria-label="俯瞰全园布局" aria-pressed={s.planView} onClick={()=>{s.home();useGarden.setState({planView:true})}}><Compass size={16}/>俯瞰全园</button></Disclosure></div>
 <div className="scene-bottom"><MiniMap/><div className="scene-caption"><span><span className="live-dot"/>{s.qualityLevel==='high'?'精细园景':'轻量园景'}{s.spoilerLimit!==null&&` · 已读至第${s.spoilerLimit}回`}</span><p><span className="desktop-gesture">拖动旋转 · 滚轮缩放 · 右键平移</span><span className="mobile-gesture">单指旋转 · 双指缩放与平移</span></p><small>依据原著整理的文学空间再现</small></div></div>
 {!simOpen&&<DetailPanel/>}<Settings/><SourcePage/><ReferenceGallery/><StoryExperience/><DreamExperience/>
 </main><SimulationPanel/></div><div className="bottom-area"><TourBar/></div></div>;
}
